[toolchain]
anchor_version = "0.31.1"

[features]
resolution = false
skip-lint = false

[programs.devnet]
cosign_escrow = "Fd9qA4pYkS43ordqGUVyYnaFZqAgRL1qZwa6nCBhC7Xq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".keys/buyer.json"

[scripts]
test = "npx tsx scripts/devnet-test.ts"
