import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { AnchorProvider, Program, type Idl } from '@coral-xyz/anchor';
import { Keypair, PublicKey, Transaction, VersionedTransaction } from '@solana/web3.js';
import { Escrow, digest } from '../src/services/escrow';
import { Runtime } from '../src/services/runtime';
import { createTask } from '../src/core/engine';
import { loadEnv, logEvidence } from './env';
import idl from '../src/data/escrow-idl.json';
import { readFileSync } from 'node:fs';

const env = loadEnv();
if (env.MOCK_MODE_SOLANA !== 'false') throw new Error('Set MOCK_MODE_SOLANA=false only at the final live setup. This test never substitutes mocked chain evidence.');
const runtime = new Runtime(env, logEvidence), escrow = new Escrow(runtime), connection = await escrow.connection();
const key = (name: string) => Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(`.keys/${name}.json`, 'utf8'))));
const buyer = key('buyer'), authority = key('authority');
const addresses = Object.fromEntries(['agent-cedar', 'agent-flint', 'agent-moss', 'agent-iris'].map(s => [s, key(s).publicKey.toBase58()]));
const task = createTask({ claim: 'Devnet escrow instruction integration test.', scenario: 'pool', payment_amount_sol: 0.001, protected: false }, { ...env, SOLANA_SELLER_ADDRESSES: JSON.stringify(addresses) });
const signTransaction = async <T extends Transaction | VersionedTransaction>(tx: T) => { if (tx instanceof VersionedTransaction) tx.sign([authority]); else tx.partialSign(authority); return tx; };
const program = new Program({ ...idl, address: env.SOLANA_PROGRAM_ID || idl.address } as Idl, new AnchorProvider(connection, { publicKey: authority.publicKey, signTransaction, signAllTransactions: async txs => Promise.all(txs.map(signTransaction)) }, { commitment: 'confirmed' }));
const [pda] = PublicKey.findProgramAddressSync([Buffer.from('escrow'), buyer.publicKey.toBuffer(), Buffer.from(await digest(task.task_id), 'hex')], program.programId);
const receipts = [await escrow.initialize(task)];
assert.equal(receipts[0].mocked, false);
const hash = await digest({ test: task.task_id }); const bytes = [...Buffer.from(hash, 'hex')];
const seller = new PublicKey(task.slots[0].address); const beforeSeller = await connection.getBalance(seller);
receipts.push(await escrow.settle(task, 0, true, hash)); assert.equal(await connection.getBalance(seller), beforeSeller + 1_000_000);
const beforeBuyer = await connection.getBalance(buyer.publicKey); receipts.push(await escrow.settle(task, 1, false, hash)); assert.equal(await connection.getBalance(buyer.publicKey), beforeBuyer + 1_000_000);
await assert.rejects(() => program.methods.release(0, bytes).accountsStrict({ authority: authority.publicKey, escrow: pda, seller }).rpc(), /AlreadySettled|Allocation already settled/);
await assert.rejects(() => program.methods.refund(1, bytes).accountsStrict({ caller: authority.publicKey, escrow: pda, buyer: buyer.publicKey }).rpc(), /AlreadySettled|Allocation already settled/);
await assert.rejects(() => program.methods.release(2, bytes).accountsStrict({ authority: authority.publicKey, escrow: pda, seller }).rpc(), /WrongRecipient|Recipient differs/);
await assert.rejects(() => program.methods.release(2, Array(32).fill(0)).accountsStrict({ authority: authority.publicKey, escrow: pda, seller: new PublicKey(task.slots[2].address) }).rpc(), /MissingEvidence|evidence commitment/);
const intruder = Keypair.generate();
await assert.rejects(() => program.methods.release(2, bytes).accountsStrict({ authority: intruder.publicKey, escrow: pda, seller: new PublicKey(task.slots[2].address) }).signers([intruder]).rpc(), /ConstraintHasOne|has one/);
await assert.rejects(() => program.methods.refund(2, bytes).accountsStrict({ caller: buyer.publicKey, escrow: pda, buyer: buyer.publicKey }).signers([buyer]).rpc(), /Unauthorized|Only the verifier/);
receipts.push(await escrow.settle(task, 2, true, hash)); receipts.push(await escrow.settle(task, 3, false, hash));
const recovered = await escrow.settle(task, 0, true, hash); assert.equal(recovered.signature, receipts[1].signature);
mkdirSync('artifacts/live', { recursive: true }); writeFileSync('artifacts/live/devnet-instructions.json', JSON.stringify({ at: new Date().toISOString(), task_id: task.task_id, receipts, assertions: ['locked', 'seller balance increased', 'buyer refunded', 'no double release', 'no double refund', 'wrong recipient rejected', 'empty evidence rejected', 'unauthorized signer rejected', 'early buyer refund rejected', 'idempotent receipt recovery'] }, null, 2));
console.log('PASS: real devnet escrow instructions, balances, authorization and replay protections.');
console.log(receipts.map(r => r.explorer_url).join('\n'));
